import json
from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Any

class BillingProvider(ABC):
    @abstractmethod
    def list_split_bill_details(self, billing_cycle: str) -> list[dict[str, Any]]: ...

class MockBillingProvider(BillingProvider):
    def list_split_bill_details(self, billing_cycle: str) -> list[dict[str, Any]]:
        return [
            {"CostID":"mock-1", "BillPeriod":billing_cycle, "ProjectID":"project-a", "PayableAmount":"9600.00", "InstanceNo":"i-a", "ProductZh":"云服务器"},
            {"CostID":"mock-2", "BillPeriod":billing_cycle, "ProjectID":"project-b", "PayableAmount":"5100.00", "InstanceNo":"i-b", "ProductZh":"对象存储"},
        ]

class VolcBillingProvider(BillingProvider):
    """Production adapter boundary.

    Paste the Python SDK call generated by Volcengine API Explorer into
    `_request_page`. Keeping it isolated prevents cloud SDK changes from
    affecting budget logic.
    """
    def __init__(self, access_key: str, secret_key: str, endpoint: str, region: str):
        self.access_key = access_key
        self.secret_key = secret_key
        self.endpoint = endpoint
        self.region = region

    def _request_page(self, billing_cycle: str, offset: int, limit: int) -> dict[str, Any]:
        raise NotImplementedError(
            "Use Volcengine API Explorer to generate ListSplitBillDetail Python SDK code, "
            "then implement this method. Required inputs: BillPeriod, Offset, Limit, NeedRecordNum=1."
        )

    def list_split_bill_details(self, billing_cycle: str) -> list[dict[str, Any]]:
        offset, limit, rows = 0, 300, []
        while True:
            response = self._request_page(billing_cycle, offset, limit)
            error = response.get("ResponseMetadata", {}).get("Error")
            if error:
                raise RuntimeError(json.dumps(error, ensure_ascii=False))
            result = response.get("Result", {})
            page = result.get("List", [])
            rows.extend(page)
            total = int(result.get("Total", len(rows)))
            if not page or len(rows) >= total:
                return rows
            offset += limit

def payable_amount(row: dict[str, Any]) -> Decimal:
    return Decimal(str(row.get("PayableAmount") or row.get("PaidAmount") or "0"))

def project_id(row: dict[str, Any]) -> str:
    return str(row.get("ProjectID") or row.get("ProjectId") or row.get("Project") or "UNASSIGNED")

def unique_key(row: dict[str, Any], billing_cycle: str = "") -> str:
    fields = [row.get("BillPeriod") or billing_cycle, row.get("CostID"), row.get("BillDetailId"), row.get("BillID"), row.get("InstanceNo"), row.get("ProjectID"), row.get("AmortizedDay")]
    return "|".join(str(v or "") for v in fields)
